### ISSUE TITLE
Crash, Pipe Visualizer [not reproducable]

### ISSUE THREAD

**Issue by some0nenew** [raiguard/PipeVisualizer#25] opened 2023-11-06 21:53 UTC
### Description

Crashed back to Main menu, was flying with the Visualizer enabled over my Oil-refinement. Was deconstructing pipes and other stuff. Could not reproduce it afterwards, because i didn't have anything left to deconstruct. Could not find a need for an immediate fix, only uploaded it to be thorough. 

The mod Pipe Visualizer (2.1.0) caused a non-recoverable error.
Please report this error to the mod author.

Error:
```
Error while running event PipeVisualizer::on_tick (ID 0)
LuaEntity API call when LuaEntity was invalid.
stack traceback:
	[C]: in function '__index'
	__PipeVisualizer__/scripts/iterator.lua:45: in function 'pop'
	__PipeVisualizer__/scripts/iterator.lua:141: in function 'iterate'
	__PipeVisualizer__/scripts/iterator.lua:269: in function 'handler'
	__core__/lualib/event_handler.lua:47: in function <__core__/lualib/event_handler.lua:45>
```

Mods:
  ```
Armor_pockets = "1.1.0",
  Automatic_Train_Painter = "1.2.0",
  BottleneckLite = "1.2.8",
  CleanFloor = "1.1.0",
  CursorEnhancements = "2.1.0",
  DeadlockStackingForPy2 = "1.1.8",
  DeadlocksStackingForPyanadon = "0.5.8",
  Enhanced_Map_Colors = "1.5.5",
  ["Flow Control"] = "3.1.4",
  FluidMustFlow = "1.3.5",
  FluidWagonColorMask = "1.1.0",
  GUI_Unifyer = "1.12.0",
  Honk = "5.0.0",
  Milestones = "1.3.20",
  ModuleInserter = "5.2.4",
  PavementDriveAssistContinued = "4.1.1",
  PickerDollies = "1.2.6",
  PipeVisualizer = "2.1.0",
  RateCalculator = "3.2.3",
  RecipeBook = "3.5.6",
  RemoteConfiguration = "1.2.3",
  Robot_Battery_Research = "0.2.1",
  StoneWaterWell = "1.20.1",
  TaskList = "0.4.7",
  UltimateResearchQueue = "1.0.12",
  Waterfill_v17 = "1.1.0",
  WireShortcuts = "1.1.13",
  ["aai-containers"] = "0.2.11",
  ["aai-loaders"] = "0.1.4",
  ["aai-signal-transmission"] = "0.4.9",
  ["aai-vehicles-ironclad"] = "0.6.8",
  ["alien-biomes"] = "0.6.8",
  ["alien-biomes-hr-terrain"] = "0.6.1",
  ["automatic-underground-pipe-connectors"] = "1.1.0",
  base = "1.1.94",
  beautiful_bridge_railway = "1.1.1",
  ["belt-reverserup"] = "0.0.9",
  bobinserters = "1.1.7",
  ["cargo-ships"] = "0.2.4",
  ["cargo-ships-graphics"] = "0.2.1",
  cybersyn = "1.3.0",
  ["cybersyn-combinator"] = "0.6.1",
  ["deadlock-beltboxes-loaders"] = "2.4.2",
  factoryplanner = "1.1.72",
  flib = "0.13.0",
  ["gas-me-up"] = "0.1.1",
  ["ghost-counter"] = "1.2.1",
  jetpack = "0.3.14",
  ["nixie-tubes"] = "1.1.3",
  pycoalprocessing = "2.1.5",
  pycoalprocessinggraphics = "2.0.8",
  pyfusionenergy = "2.0.6",
  pyfusionenergygraphics = "2.0.1",
  pyhightech = "2.0.10",
  pyhightechgraphics = "2.0.2",
  pyindustry = "2.0.10",
  pypetroleumhandling = "2.1.10",
  pypetroleumhandlinggraphics = "2.0.1",
  pypostprocessing = "0.2.14",
  pyrawores = "2.4.10",
  pyraworesgraphics = "2.0.2",
  ["rso-mod"] = "6.2.25",
  ["rusty-locale"] = "1.0.16",
  simhelper = "1.1.5",
  stdlib = "1.4.8",
  textplates = "0.6.10"


```

[factorio-current.log](https://github.com/raiguard/PipeVisualizer/files/13272916/factorio-current.log)

**Comment by mheidal** [comment] 2023-11-17 07:27
I experienced the same crash. This is my crash report:
```
The mod Pipe Visualizer (2.1.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event PipeVisualizer::on_tick (ID 0)
LuaEntity API call when LuaEntity was invalid.
stack traceback:
	[C]: in function '__index'

	__PipeVisualizer__/scripts/iterator.lua:45: in function 'pop'
	__PipeVisualizer__/scripts/iterator.lua:141: in function 'iterate'
	__PipeVisualizer__/scripts/iterator.lua:269: in function 'handler'
	__core__/lualib/event_handler.lua:47: in function <__core__/lualib/event_handler.lua:45>
```

Log: [factorio-current.log](https://github.com/raiguard/PipeVisualizer/files/13388480/factorio-current.log)


Reproduce:
[pipe visualizer crash repro.zip](https://github.com/raiguard/PipeVisualizer/files/13388711/pipe.visualizer.crash.repro.zip)
Download this save file with Pipe Visualizer installed. Swap to coloring by fluid system. Copy the pipes that are on the ground, then paste them a bunch of times. After some of the pipes have been placed, mark them for deconstruction and spam the keybind to toggle the visualizer. The game should crash.

Video of the crash: https://drive.google.com/file/d/1Jt8_qwlm5tcaen9yWysUnpvAd5wfruHs/view?usp=sharing

**Comment by raiguard** [comment] 2023-11-24 20:02
Duplicate of #21

**Closed as not planned by raiguard** 2023-11-24 20:02 UTC
